name: build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOS: windows
      GOARCH: amd64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: cli
          path: wwise-cli.exe
